### ISSUE TITLE
Rethrow should take a label immediate

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/exception-handling#10]
Try blocks can nest, so something like this can occur:
```
try
  ...
catch
  ...
  try
    ...
  catch
    ...
    rethrow  ;; which?
  end
end
```
There can be cases where you need to rethrow the outer exception. We should avoid the popular mistake of only providing one built-in (here, implicit) name for something for which several bindings can be in scope.

Thus, I propose that `rethrow` should have a label immediate referencing the desired `try`.

**Comment by KarlSchimpf** [comment]
I see some merit in this proposal. This proposal doesn't define a "finally" version of catch blocks. However, it can be introduced by enclosing the code as following

try
  ...
     try
        ...
        try
            ...
        catch
            ...
            rethrow 1
        end
     catch
         ...
         rethrow 0
    end
else
   ... // finally code
end

**Comment by KarlSchimpf** [comment]
The problem I see is if we add a "finally" concept to try blocks, then ret

**Comment by KarlSchimpf** [comment]
This appears to define conflicting rules about catches. What if an intervening try block has a catch for the rethrow ? Who wins and why?

**Comment by rossberg** [comment]
@KarlSchimpf, this only affects which (implicitly named) exception gets thrown, not which handlers are responsible. Cf. with this Java:
```
try {
  ... 
} catch (E e1) {
  try {
    ...
  } catch (E e2) {
    throw eN;  // can pick either e1 or e2
  }
}
```

**Comment by KarlSchimpf** [comment]
@rossberg-chromium Good point. I hadn't thought of that. Will change the `rethrow` instruction to reference the corresponding catch block, based on nesting where zero corresponds to the immediate enclosing catch block.

**Comment by Abion47** [comment]
But what if in rossberg's example, you wanted to throw `e1` if the handling code of the nested `try` block fails? For example, in the current proposal, how would you manage something like this:

```
try
  ...
catch e1
  try 
    ...
  catch e2
    rethrow e1 // ??
  end
end
```

**Comment by KarlSchimpf** [comment]
PR #12 has been update to make the rethrow get a label as an argument. That is, a relative (block) index.

So for this example, `rethrow e2` would be encoded as `rethrow 0` and `rethrow e1` would be encoded as `rethrow 1`.

**Comment by Abion47** [comment]
For the sake of argument, what would happen then if I were to do this?

```
try
  ...
catch_all
  rethrow 99
end

**Comment by binji** [comment]
It would be a validation error, just as if you did
```
block
  br 99
end
```

**Comment by Abion47** [comment]
Fair enough.

**Comment by KarlSchimpf** [comment]
I assume that we are in agreement on using a label to define the rethrown exception. Closing. If you disagree, feel free to reopen.
