### ISSUE TITLE
Rethrow after access to the exnref parameters

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/exception-handling#106]
Is there a _simple_ solution to `rethrow` an exception after access to the parameters of the `exnref`?

Currently the only solution seems to be:
* save the exception in a local variable
* push the exception on the stack
* pushes the exception's argument values on top of the stack with `br_on_exn`
* inspect the arguments
* `rethrow` depending the inspection result

Sounds not very efficient. I am also not clear if a `rethrow` is possible after a `br_on_exn`.

Background: I am working on a compiler for Java ([JWebAssembly](https://github.com/i-net-software/JWebAssembly)). The exception there are hierarchical. That I can not use the plain exception type of this spec. I use only one event type. In the parameters of `exnref` there are the hierarchical exception details.

**Comment by aheejin** [comment]
`rethrow` is possible after `br_on_exn`. And I think you're right that you need to save `exnref` (pushed onto the stack by `catch`) to a local to rethrow it again. This is not a problem specific to exnref; wasm is a stack machine, and if you want to use a value on top of the stack (pushed by any instruction) twice, you need to save it to a local, for any instruction.

**Comment by Horcrux7** [comment]
Thanks.
