### ISSUE TITLE
"The representation of an exception is left to the implementation."

### ISSUE THREAD

**Issue by sabine** [WebAssembly/exception-handling#111]
I read that [the representation of an exception is left to the implementation](https://github.com/WebAssembly/exception-handling/blame/4d3526bf6c2c0d349ccd8e9eefd450575fe3c4e1/proposals/Exceptions.md#L149).

Does that mean, when implementing a compiler from another language to WebAssembly, if the exception handling proposal goes through, we have to write different code for every WASM target (e.g. browser) we want to compile to, in order to make use of the exception handling facilities?

I can see that, different embedders may have different stack trace facilities, or other exception-related information attached to an exception value, and thus, it may not be reasonable to expect everyone to use the same representation of exceptions. That's fine.

I'm wondering how this proposal will work for languages who want to implement their own exception mechanism in terms of WebAssembly exceptions/events. Is there anything I should look at?

**Comment by dschuff** [comment]
No, that statement means that the representation of the language's exception type (e.g. C++) is left to the language implementation. All implementations of wasm should behave the same, but the wasm exception mechanism is fairly primitive, so a language exception will probably have more information than just an exnref. As a language implementer, you can attach whatever [type](https://github.com/WebAssembly/exception-handling/blame/4d3526bf6c2c0d349ccd8e9eefd450575fe3c4e1/proposals/Exceptions.md#L120) you want to your event, and then values of that type will be consumed when you throw, and produced when you use `br_on_exn`. (e.g. in C++ this value is just a pointer to a C++ object, but it can also be multiple values).

**Comment by sabine** [comment]
Ah, sorry about the misunderstanding then, I understood this as the implementation of the WASM engine.

Yes, I agree, every language has its own way of representing its own exceptions and attaching a type to the event makes that possible.
