### ISSUE TITLE
exnref name vs. externref

### ISSUE THREAD

**Issue by jayphelps** [WebAssembly/exception-handling#114]
Since anyref was changed to only be opaque _host_ references and thus [renamed to externref](https://github.com/WebAssembly/reference-types/pull/87) I wanted to voice my opinion that the name "exnref" is too close to externref. Definitely bikeshedding--and we don't have to make any decisions immediately per say--but I wanted to bring it up in case the actual solution was to rename externref instead of exnref (probably not, but ?)

I don't have any preferred alternative names at this point, but seems like adding a c and/or p in there could be one way. Or alternatively there's been talk floated over the years several times about the future of this primitive being used for other non-exceptional events, in which case maybe a name more similar to event would be appropriate.

If there was discussion elsewhere about this that I missed (e.g. CG meeting I missed), apologies. This kinda sucks since it was [already changed at least once before](https://github.com/WebAssembly/exception-handling/issues/79). Ultimately I just wanted to at least plant the discussion flag before any ships sail and see if I'm alone in this.

**Comment by aheejin** [comment]
Yes it's not great that they became similar, but I'm also not sure if if is a problem. If you have a good alternative name, please suggest.

**Comment by aheejin** [comment]
Closing this, as we decided to remove `exnref` in Sep 15 CG meeting.
