### ISSUE TITLE
Opcode for delegate

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/exception-handling#145]
In #137 it's mentioned that the opcode for `delegate` needs to be decided. Has there been any discussion of that yet?

As mentioned in #137, the `0x0?` opcodes are used up. I believe the [V8 code](https://github.com/v8/v8/commit/8eb97f5a4bcbaa77c85f3e7be9eb43bfa4d0819d) is currently using `0x16` as a placeholder, but I think that and `0x17` are used by the [function references](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md) proposal.

It looks like `0x18` or `0x19` may be available though based on looking through the current proposals.

**Comment by aheejin** [comment]
Following V8 implementation, I was tentatively using `0x16` in my toolchain implementation, but given that it is already takne, we should probably change it to `0x18` or `0x19` as you suggested. How about `0x18`? @thibaudmichaud

**Comment by thibaudmichaud** [comment]
Thanks for pointing out the conflict with function references, @takikawa. `0x18` sounds good.
