### ISSUE TITLE
Match delegate's immediate and label argument to those of branches

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/exception-handling#146]
I'd like to suggest a slight change to the current seemingly discussed spec in #143 so that we can treat the target of `br`s and `delegate`s in a similar way in the wast format. I think this will help reading and writing the wast format and spec tests.

I'm not actually very sure if this will be a suggestion to  _change_, because after discussions w/ @thibaudmichaud I realized my understanding was different from his and what I'd like to suggest here was actually already more in line with his V8
implementation. (Now I think we two are on the same page.)

So what I'd like to achieve is we can write the argument of `delegate` as labels in the wast format, as we do for `br`/`br_if`s, and make `delegate` can syntactically target a `try`, which semantically in turn goes to that `try`'s corresponding `catch`. `delegate`'s immediate argument is translated to the labels in the same way we do for `br`s. Let me illustrate that with an example. I annotated `catch`es with their corresponding `try`'s labels just to make it more readable. The example looks a bit long, but please bear with me:
```wasm
try $labelA
catch ($labelA)
  block $labelB
    try $labelC
      br 0         (= br $labelC)
      br 1         (= br $labelB)
      br 2         (= br $labelA)
      try
      delegate 0   (= delegate $labelC, which delegates to 'catch ($labelC)')
      try
      delegate 1   (= delegate $labelB, which is a block, so validation failure)
      try
      delegate 2   (= delegate $labelA, which delegates to 'catch ($labelA)', but 'catch ($labelA)' is above this instruction, so validation failure)
      try
      delegate 3   (= delegate to the caller)
    catch ($labelC)
      br 0         (= br $labelC)
      br 1         (= br $labelB)
      br 2         (= br $labelA)
      try
      delegate 0   (= delegate $labelC, which delegates to 'catch ($labelC)', but 'catch ($labelC)' is above this instruction, so validation failure)
      try
      delegate 1   (= delegate $labelB, which is a block, so validation failure)
      try
      delegate 2   (= delegate $labelA, which delegates to 'catch ($labelA)', but 'catch ($labelA)' is above this instruction, so validation failure)
      try
      delegate 3   (= delegate to the caller)
    end  ;; try $labelC
  end ;; block $labelB
end ;; try $labelA
```

(catches can be either `catch` or `catch_all`, it doesn't really matter here. `unwind` will be treated the same.)

So what I propose is basically this: Treat `delegate`'s immediate/label in the same way as `br`'s immediate/label. `delegate` also can target any of `block`/`loop`/`try`, but if the target is a `block` or `loop` it is a validation failure. (I think this was discussed somewhat already in #143).

If the target is a `try`, if the `try`'s corresponding `catch` is _below_ the `delegate` as in the first `delegate 0` in my example, it delegates to that `catch`. If the corresponding `catch` is _above_ the `delegate` as in the second `delegate 0` in my example, we can't delegate to somewhere upwards, so it is a validation failure. Please notice the difference between two `delegate 0`'s interpretation in my example. But the advantage of this format is we can maintain a single control flow stack,  and use labels and immediates interchangeably in the wast format as we already do for `br`/`br_if`. In my example `br`s are just written to show that when `br`'s immediate and `delegate`'s immediate are the same, their label arguments will also be the same.

Also, when there are multiple `catch`/`catch_all`s per `try`, they are treated as a chunk. So
```wasm
try $labelA
catch tag_a ($labelA)
  try
  delegate 0  ;; validation failure
catch tag_b
  ...
catch_all
  ...
end
```
`delegate 0` here targets $labelA's all catches as a chunk. Because `catch tag_a` is above this `delegate 0`, this is rather a validation failure, and it does not delegate to `catch tag_b` or `catch_all` below.

I'm not necessarily trying to discuss the formal spec yet; if we are all on the same page on the operational semantics in informal English, I think we can proceed to the format version.

WDYT? cc @thibaudmichaud @backes @ioannad @takikawa @tlively

**Comment by tlively** [comment]
Sounds good to me! I think this is in line with my own previous assumptions as well.

**Comment by thibaudmichaud** [comment]
Thanks! Sounds like we are still on the same page.

**Comment by backes** [comment]
Thanks for the write-up. Looks good to me!

**Comment by rossberg** [comment]
Sounds good, that already was my assumption as well.

**Comment by takikawa** [comment]
Thanks for the clarification! It sounds good to me and I think it matches my mental model of the semantics.

I just wanted to get clarification on one thing, sorry if I missed this somewhere in the write-up. If a `delegate N` targets an outer `try-delegate` block, that should also validate right? Judging from the write-up where it says "delegate also can target any of block/loop/try", I was assuming this is the case, but I wanted to make sure.

**Comment by aheejin** [comment]
@takikawa Yes, `delegate` can target either a try-catch or a try-delegate. (If if targets something else, such as blocks or loops, it will be a validation error.)

**Comment by ioannad** [comment]
Full agreement from me too, @aheejin.

**Comment by aheejin** [comment]
Can we assume `rethrow` follows the same rule? The current explainer (#137) says

---

Associated with the `rethrow` instruction is a _label_. The label is used to
disambiguate which exception is to be rethrown, when inside nested catch blocks.
The label is the relative block depth to the corresponding try block for which
the catching block appears.

For example consider the following:

```wasm
try
  ...
catch 1
  ...
  block
    ...
    try
      ...
    catch 2
      ...
      try
        ...
      catch 3
        ...
        rethrow N
      end
    end
  end
  ...
end
```

In this example, `N` is used to disambiguate which caught exception is being
rethrown. It could rethrow any of the three caught expceptions. Hence,
`rethrow 0` corresponds to the exception caught by `catch 3`, `rethrow 1`
corresponds to the exception caught by `catch 2`, and `rethrow 3` corresponds
to the exception caught by `catch 1`.

Note that `rethrow 2` is not allowed because it does not reference a `try`
instruction. Rather, it references a `block` instruction.

---

I didn't invent this rule for the explainer myself; I simply restored the old rule from [the very first version of the spec](https://github.com/WebAssembly/exception-handling/blob/1ec111eb32c8490991c943af2af40559dbd63cd4/proposals/exception-handling/old/Exceptions-v1.md), which is similar to the current spec except the current spec has `unwind` and `delegate` additionally. But this looks in line with the rule we agreed on for `delegate` as well. So the example above can be rewritten in the text format using labels:
```wasm
try $label1
  ...
catch ($label1)
  ...
  block $label2
    ...
    try $label3
      ...
    catch ($label3)
      ...
      try $label4
        ...
      catch ($label4)
        ...
        ;; These two rethrow the exception caught by catch ($label4)
        rethrow $label4
        rethrow 0
        ;; These two rethrow the exception caught by catch ($label3)
        rethrow $label3
        rethrow 1
        ;; These correspond to the block $label2, so validation failure
        rethrow $label2
        rethrow 2
        ;; These two rethrow the exception caught by catch ($label1)
        rethrow $label1
        rethrow 3
      end
    end
  end
  ...
end
```

Do we also agree on this?

**Comment by aheejin** [comment]
Oh, also, to make `rethrow` follow the same immediate/label rule with branches and delegates, when `rethrow` is between `try` and `catch`. I added some more lines to the previous example. Here all other cases are the same, but `rethrow 0` is a validation failure.

```wasm
try $label1
  ...
catch ($label1)
  ...
  block $label2
    ...
    try $label3
      ...
    catch ($label3)
      ...
      try $label4
        ...
        ;; These two refers to 'catch (label$4)', but it is not within 'catch (label$4)', so validation failure
        rethrow $label4
        rethrow 0
        ;; These two rethrow the exception caught by catch ($label3)
        rethrow $label3
        rethrow 1
        ;; These correspond to the block $label2, so validation failure
        rethrow $label2
        rethrow 2
        ;; These two rethrow the exception caught by catch ($label1)
        rethrow $label1
        rethrow 3
      catch ($label4)
        ...
        ;; These two rethrow the exception caught by catch ($label4)
        rethrow $label4
        rethrow 0
        ;; These two rethrow the exception caught by catch ($label3)
        rethrow $label3
        rethrow 1
        ;; These correspond to the block $label2, so validation failure
        rethrow $label2
        rethrow 2
        ;; These two rethrow the exception caught by catch ($label1)
        rethrow $label1
        rethrow 3
      end
    end
  end
  ...
end
```

**Comment by thibaudmichaud** [comment]
Thanks for the examples, they still match my expectation and V8's implementation so far.

**Comment by takikawa** [comment]
@aheejin Thanks for clarifying this. Based on [previous examples from this PR](https://github.com/WebAssembly/exception-handling/pull/143#issuecomment-747276500) (example 2 there) my understanding had been that the current interpretation was that `rethrow`'s argument only counts catch blocks.

But I'm also happy to implement this interpretation of the `rethrow` argument which aligns it with `br`, `delegate`, etc. because it is simpler and consistent with everything else too.

**Comment by aheejin** [comment]
@takikawa Sorry, yeah, I was mistaken about the rule too, but while discussing the impl with @thibaudmichaud I realized the Explainer says it uses the same rule with branches (and delegates).

**Comment by ioannad** [comment]
@aheejin SGTM too! I am updating the formal-spec-overview now, and it seems the semantics as agreed in this issue do make things simpler. Although we're back to a new attribute (this time I call it `kind`) of labels surrounding instructions in `try` blocks or `catch` blocks, that's ok imho. No more `Caught` stack so :+1: :)
