### ISSUE TITLE
Implement event->tag renaming in core tests

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/exception-handling#169]
The recently merged core tests in #160 still use the event terminology, so they need to be renamed to tag for compatibility with issue #159. This was already brought up in the discussion thread in #160, but I'm filing this issue so it's tracked somewhere (it'd be useful for importing the spec tests for tooling/browser test suites).

Is someone working on this change already? (@thibaudmichaud maybe?) If not I could work on a PR.

**Comment by thibaudmichaud** [comment]
I haven't started working on this change yet, you can take it. Thanks!

**Comment by takikawa** [comment]
Fixed by #170.
