### ISSUE TITLE
Implement validation & evaluation in the spec interpreter

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/exception-handling#171]
Assuming things go smoothly for stage 3, one of the stage 4 requirements is "The formalization and the reference interpreter are usually updated". The current interpreter landed in #160 has encoding/decoding/parsing for testing but needs validation and evaluation support.

There's been some previous work on interpreter support for validation and evaluation of different exception semantics (like the previous iteration of the proposal):

  * https://github.com/effect-handlers/wasm-effect-handlers/tree/exception-handlers
  * https://github.com/effect-handlers/wasm-spec (this implements a minimal version that's neither the new or old spec I think)

But I'm not aware of updated code for the current proposal semantics.

I'm happy to work on PRs for this if nobody else is currently working on it.

**Comment by aheejin** [comment]
cc @thibaudmichaud

**Comment by thibaudmichaud** [comment]
I'm not working on this currently, thanks for volunteering!

**Comment by takikawa** [comment]
Fixed in #175
