### ISSUE TITLE
Exceptions have a method `getArg` but parameters are the WASM signature's result types

### ISSUE THREAD

**Issue by kmiller68** [WebAssembly/exception-handling#184]
Probably a nit but it seems like "arg" might be the wrong term. Perhaps it should be something more generic like `at`. `at` also has the upside of working nicely with anything that takes a list in the DOM.

Since it seems silly to make a new issue for something so small but perhaps we should throw a `RangeError` instead of a `TypeError` if the requested index out of bounds?

**Comment by kmiller68** [comment]
Actually, I think I was misreading the JS spec. They are arguments and not results in the WASM Signature. That said, I think the other questions are still valid.

**Comment by kmiller68** [comment]
I also don't quite understand why `getArg` also requires a `tag` as the first parameter.

**Comment by Ms2ger** [comment]
I'm not sure what you mean by "working nicely with anything that takes a list in the DOM" - you need to pass the tag, so it's not like you can treat it as a list directly.

I guess I don't see either change as much of an improvement, but I don't care deeply either way.
