### ISSUE TITLE
Should catch blocks be nested inside try blocks.

### ISSUE THREAD

**Issue by KarlSchimpf** [WebAssembly/exception-handling#2]
The current proposal defines catch blocks and nested "catch" ... "end" blocks within the corresponding "try" ... "end" block.

Nesting the blocks makes several parts of the proposal a bit clumsy.

**Comment by KarlSchimpf** [comment]
Adding comment from @rossberg-chromium:

I would assume that catch isn't a separate block instruction at all, but part of the try, in the same way else is part of if. Roughly, the syntax would be:

try <blocktype> <instr>* (catch <idx> <instr>*)* (default <instr>*) end

**Comment by kmiller68** [comment]
How would this work for nested trys? i.e. how would you which try the catch belongs to?

Presumably catch would have to have some index indicating the try to which it belongs, similar to br/br_if.

Edit: Nvm if try has an end opcode this isn't an issue. Ignore me...

**Comment by KarlSchimpf** [comment]
I agree that catches must be tied to a try block. This can be done syntactically, or it can be done as you suggest with an index. I had meant it to be syntactic. That is, I was proposing the syntax:

try
  ...
  catch i
    ...
  end
  catch j
  ...
  end
end

In this context the catch only applies to the (immediate) enclosing block. Some have suggested a better syntax that makes this connection stronger. That is, the construct has the form

   try ... catch i ... catch j ... end

With this syntax, the association of the catches is explicit in the construct itself.

Right now, I am leaning towards the view of using the flat syntax (second case).

**Comment by KarlSchimpf** [comment]
Pull request #6 follows the basic suggestion of @ross

**Comment by KarlSchimpf** [comment]
Since there hasn't been comments on this issue in 10 days, closing. Feel free to reopen if you want to make additional comments.
