### ISSUE TITLE
Port stack trace support from explainer to js api spec

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/exception-handling#201]
#197

**Comment by aheejin** [comment]
Are you planning on working on this in near future?

**Comment by hamishwillee** [comment]
Not having this in the spec is problematic for MDN docs and browser compatibility data. We're supposed to doc what the spec does, so if the spec is not updated we should document  browsers that implement as per the explainer as "off-spec". Firefox 100 is such a browser according to https://bugzilla.mozilla.org/show_bug.cgi?id=1759217#c6

Is there an ETA for this to happen?

**Comment by aheejin** [comment]
Friendly ping! :) Sorry for bugging you again, but it'd be good to know what your plan on this is. Are you planning to working on this? If so, can you let me know the rough timeline?

If you are unable to work on this for a long time, I can try working on this, but I'm no expert on JS API formal spec at all, so I guess I would at least very much appreciate your reviews. Also about #189 as well.

Please let me know what your plan is. Thanks!

**Comment by Ms2ger** [comment]
Hey, sorry about the delay. I should have more time to work on wasm again from July - if you have time before that, I'll try to find time to review.

**Comment by aheejin** [comment]
@Ms2ger Do you have a plan to, or have availability to work on this in Q3? I am hoping we can advance the proposal to phase 4 by the end of Q3, so I'm wondering about this. Thank you!
