### ISSUE TITLE
Ambiguous wording regarding the optionality of stack tracing attachments

### ISSUE THREAD

**Issue by ghost** [WebAssembly/exception-handling#215]
https://github.com/WebAssembly/exception-handling/blob/74e7aa69fedac46255bf48e0b8600889270d6037/proposals/exception-handling/Exceptions.md#L452-L454

The use of "can" here makes it seem as if attaching a stack trace is optional, and possibly up to the whim of the host/engine? Can this be reworded to make it obvious as to which way it is intended to be interpreted?

**Comment by aheejin** [comment]
Yes, "can" means it is optional. It being optional is explained in more detail in [the JS API section](https://github.com/WebAssembly/exception-handling/blob/74e7aa69fedac46255bf48e0b8600889270d6037/proposals/exception-handling/Exceptions.md#js-api).

**Comment by ghost** [comment]
> Yes, "can" means it is optional. It being optional is explained in more detail in [the JS API section](https://github.com/WebAssembly/exception-handling/blob/74e7aa69fedac46255bf48e0b8600889270d6037/proposals/exception-handling/Exceptions.md#js-api).

Can you elaborate, and/or point out any specific sentences that explain that? For clarification, the snippet that I refer to is from is in that very section that you also reference.

**Comment by aheejin** [comment]
This is the sentence that explains the optionality:
https://github.com/WebAssembly/exception-handling/blob/74e7aa69fedac46255bf48e0b8600889270d6037/proposals/exception-handling/Exceptions.md?plain=1#L451-L454

Also note that the optional `ExceptionOptions` argument, which contains stack trace:
https://github.com/WebAssembly/exception-handling/blob/74e7aa69fedac46255bf48e0b8600889270d6037/proposals/exception-handling/Exceptions.md?plain=1#L479-L489

**Comment by ghost** [comment]
I'm not certain as to whether we have the same idea in mind; I am asking whether the engine may still not attach the trace, even if `traceStack` is `true`?
E.g.,
```js
const tag = new Tag();
const exception = new Exception(tag, [], { traceStack: true });
const did_attach_stack_trace = undefined !== exception.stack;
```
Here, is it possible that `exception.stack` is `undefined`, regardless of the parameter provided?
This is what I consider ambiguous by the current writing.

**Comment by aheejin** [comment]
Ah I see. Yeah, all web Wasm engines have the capability to attach stack traces, but there can be other non-web engines without that, in which case they don't need to error out; they can "not attach" stack traces. If the current wording seems unclear, I'd appreciate PRs or suggestions.

**Comment by ghost** [comment]
@aheejin And a quick question before I attempt a PR, to get a better understanding of this, is an engine permitted to attach the stack trace even if `traceStack` is false?

I believe my problem with this currently is in part that `traceStack` sounds like a directive, demanding that it is or isn't performed, yet it may act as more of a hint or request?

**Comment by aheejin** [comment]
> @aheejin And a quick question before I attempt a PR, to get a better understanding of this, is an engine permitted to attach the stack trace even if `traceStack` is false?

No.

> I believe my problem with this currently is in part that `traceStack` sounds like a directive, demanding that it is or isn't performed, yet it may act as more of a hint or request?

Request sounds the most appropriate word here. So it is like "If you have the capability, attach stack traces". If the engine can't do that it's fine not do to it.
