### ISSUE TITLE
Can catch clauses in `try_table` refer to itself?

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/exception-handling#286]
[Ref to the spec](https://webassembly.github.io/exception-handling/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-try-table-xref-syntax-instructions-syntax-blocktype-mathit-blocktype-xref-syntax-instructions-syntax-catch-mathit-catch-ast-xref-syntax-instructions-syntax-instr-mathit-instr-ast-xref-syntax-instructions-syntax-instr-control-mathsf-end).

It looks like catch clauses are validated under a context that does not include the label for the try_table itself.

So the following would be invalid:
```
try_table $handleExn (catch_all $handleExn)

  ;; do stuff
  return

end
;; handle the exception
```

However, it seems like the above could be a useful pattern for avoiding an extra block in certain cases. It is also how I originally implemented in SM and was pretty straightforward.

cc @rossberg

**Comment by aheejin** [comment]
It is invalid in my understanding too. I think it is because it conforms to the same rule as `br`, and I think it's clearer this way.

**Comment by rossberg** [comment]
The scoping of labels is designed to be independent of the flavour of block instruction: that is, label indices are only in scope _inside_ a nested block, and a block merely consists of the nested _instruction sequence_, agnostic to the sort of block instruction that contains it. The catch handlers o.t.o.h. are part of the instruction header, not of the nested block, so the label isn't in scope there and no special scoping rule exists for them. That also happens to make try_table consistent with how try-delegate scoped before.

**Comment by titzer** [comment]
In other words, since these labels are immediates to the `try_table`, the `try_table` hasn't been entered when they are processed. The first instruction after the `try_table` is the first where its label would be valid. This tripped me up too when I implemented it in Wizard, but there are tests for it.

**Comment by eqrion** [comment]
> The scoping of labels is designed to be independent of the flavour of block instruction: that is, label indices are only in scope _inside_ a nested block, and a block merely consists of the nested _instruction sequence_, agnostic to the sort of block instruction that contains it. The catch handlers o.t.o.h. are part of the instruction header, not of the nested block, so the label isn't in scope there and no special scoping rule exists for them. That also happens to make try_table consistent with how try-delegate scoped before.

Hmm. I guess I'm not sure the reason why the catch handlers being an immediate to the instruction means that semantically they must occur before the nested block is entered into. It would seem equally valid to say that the nested block is entered first and then the catch handlers are registered.

Concretely too, I've used the pattern in the OP before to save writing out extra blocks in certain cases. So it seems like it could be beneficial.

But it's not the biggest deal either way, so fine to leave it as is too.
