### ISSUE TITLE
question about labels in catch clauses

### ISSUE THREAD

**Issue by yamt** [WebAssembly/exception-handling#288]
can these labels target only `block` blocks?
or can they be other type of blocks, like `loop` and `try_table`, and even function exit?

**Comment by rossberg** [comment]
Wasm doesn't distinguish label kinds, so yes, any label with the right type is allowed.

**Comment by yamt** [comment]
ok. thank you.

**Comment by aheejin** [comment]
Given that it looks resolved, will close this.
