### ISSUE TITLE
seemingly broken html rendering

### ISSUE THREAD

**Issue by yamt** [WebAssembly/exception-handling#292]
seemingly broken html rendering on https://webassembly.github.io/exception-handling/core/appendix/index-instructions.html

<img width="1027" alt="Screen Shot 2024-01-28 at 14 17 19" src="https://github.com/WebAssembly/exception-handling/assets/1845377/b889ba0f-2f53-4194-ae55-a2d928a2b513">

it's firefox on macOS if it matters.

**Comment by rossberg** [comment]
Thanks, should be fixed now.
