### ISSUE TITLE
Noexn type

### ISSUE THREAD

**Issue by thibaudmichaud** [WebAssembly/exception-handling#297]
#282 included the notion of a noexn type to mirror the other null types of the GC proposal, but this was not added in the spec yet.
Should it be added, and do we already have an opcode for it?

**Comment by aheejin** [comment]
I think we should add the opcode. Binaryen also needed it to implement EH. I currently encode it as `0xff` for a placeholder: https://github.com/WebAssembly/binaryen/blob/feb8f24128c0c3bd53862b2f39acc5116f8ae87e/src/wasm-binary.h#L478

**Comment by rossberg** [comment]
Right, this is another example of some feature falling into the intersection of two proposals. Since GC has advanced to phase 4 now, it should be added here. (At least in the overview, in the actual spec we'll need to wait until we rebase on the spec including GC.)

**Comment by rossberg** [comment]
Please see #298.

**Comment by aheejin** [comment]
Closed by #298.
