### ISSUE TITLE
Should there be a separate exception type section.

### ISSUE THREAD

**Issue by KarlSchimpf** [WebAssembly/exception-handling#3]
The proposal introduces exception types. Should there be a separate type section, or should they be merged into the type section.

**Comment by KarlSchimpf** [comment]
Adding comment by @rossberg-chromium 

This ties in with my other comment: they shouldn't be defined as types in the first place. They are values (tags).

**Comment by flagxor** [comment]
I would think we only need a type for them if you can pass them around.
We went through the motions of treating function signatures and basic types as if they're in the same space, but I'm unsure if that has any real utility yet. I.e. we don't currently have a way to pass around a value with a function type.

**Comment by KarlSchimpf** [comment]
PR #6 has an "exception" section that references function types in the type section. The function type is for exception construction.

**Comment by KarlSchimpf** [comment]
The exception section in the proposal now defines the tuple of user-available values in an exception. Similarly, imported exceptions define the tuple of user-available values. This seems cleaner. Closing this issue. If you disagree, you can reopen this issue.
