### ISSUE TITLE
Issues with the README

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/exception-handling#310]
The README says this:

> In case of `catch` or `catch_ref`, the arguments of the exception are pushed back onto the stack. For `catch_ref` and `catch_all_ref`, an exception reference is then pushed to the stack, which represents the caught exception.

I may be wrong, but this just seemed inconsistent. I would assume it should say this:

> In case of `catch` or *`catch_all`*, the arguments of the exception are pushed back onto the stack. For `catch_ref` and `catch_all_ref`, an exception reference is then pushed to the stack, which represents the caught exception.

There's also a minor typo in the following line (it misspells *caught* as *cought*):

> All forms have a label which is branched to when an exception is cought (see below).

I didn't want to become a "contributor" for such a trivial pull request, so just opened an issue here instead.

**Comment by sjrd** [comment]
> I may be wrong, but this just seemed inconsistent. I would assume it should say this:

The readme is correct on that point. The non-`_all` variants push the arguments. The `_ref` variants push a ref. Therefore: 
* `catch_all`: nothing on the stack
* `catch`: the arguments on the stack
* `catch_all_ref`: the ref on the stack
* `catch_ref`: the arguments *and* the ref on the stack

**Comment by aheejin** [comment]
Thanks for the info!

> The README says this:
> 
> > In case of `catch` or `catch_ref`, the arguments of the exception are pushed back onto the stack. For `catch_ref` and `catch_all_ref`, an exception reference is then pushed to the stack, which represents the caught exception.
> 
> I may be wrong, but this just seemed inconsistent. I would assume it should say this:
> 
> > In case of `catch` or _`catch_all`_, the arguments of the exception are pushed back onto the stack. For `catch_ref` and `catch_all_ref`, an exception reference is then pushed to the stack, which represents the caught exception.

I think it should be just "in case of `catch`", because `catch_all` does not push anything onto the stack.

**Comment by aheejin** [comment]
Please ignore the previous comment (now deleted) of mine here; I was confused and posted some incorrect info.

**Comment by 7ombie** [comment]
No worries, @aheejin. Glad it's all correct, either way. Sorry for any noise on my part.
