### ISSUE TITLE
Typo in description of catch clause behavior

### ISSUE THREAD

**Issue by danlliu** [WebAssembly/exception-handling#323]
> Then catch clauses are tried in the order they appear in the catching try block, until one matches. If a matching catch clause is found, control is transferred to the label of that catch clause. In case of catch or **catch_ref**, the arguments of the exception are pushed back onto the stack. For catch_ref and catch_all_ref, an exception reference is then pushed to the stack, which represents the caught exception.

(emphasis mine)

Is the first `catch_ref` supposed to be `catch_all` here? It doesn't quite feel correct to have `catch_ref` brought up twice, and `catch_all` not mentioned, but wanted to confirm this.

**Comment by aheejin** [comment]
No it is correct. This comment summarizes it well: https://github.com/WebAssembly/exception-handling/issues/310#issuecomment-2183234729
