### ISSUE TITLE
Can catch_ref / catch_all_ref's destinations have type (ref exn)?

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/exception-handling#336]
Can `catch_ref` or `catch_all_ref`'s destination blocks have a non-nullable exnref as the return type?
```wast
block (ref exn)
  try_table (catch_all_ref 0)
    ...
  end
end
```

The current EH spec interpreter does not handle `(ref ..)` keyword (it is included in the GC spec), so I can't test this with the current interpreter. The formal spec only says `exnref`. Does this mean it can't be `(ref exn)`?

**Comment by rossberg** [comment]
Yes. For example, this type-checks with the interpreter on the wasm-3.0 branch:
```wast
(module
  (func (result (ref exn))
    (try_table (catch_all_ref 0))
    (unreachable)
  )
)
```

**Comment by aheejin** [comment]
Thanks!
