### ISSUE TITLE
JS Embedding: When to capture stack trace

### ISSUE THREAD

**Issue by eholk** [WebAssembly/exception-handling#37]
The current Layer 1 proposal splits creating the exception object from throwing it. JavaScript exceptions usually have a stack trace associated with them. Should the embedding capture the stack trace at the point the exception is created, or when it is thrown?

See https://github.com/WebAssembly/exception-handling/pull/33#discussion_r167328416

**Comment by erights** [comment]
For reference, https://github.com/tc39/proposal-error-stacks is the current proposal to standardize JavaScript error stacks.

**Comment by eholk** [comment]
Thanks!

From quickly skimming that, I assume the stack data is captured when you do `new Error()`, rather than at the point where you do `throw`? If so, it would make sense for Wasm to follow that behavior as well in the JS embedding.

**Comment by erights** [comment]
Hi @eholk , yes. Likewise, rethrowing has no effect on the captured stack trace.

It makes sense to me as well for wasm to follow this precedent. Thanks.

**Comment by aheejin** [comment]
Now we do both creation and throwing with a single `throw` instruction. We can create JS API that creates and throws wasm exceptions, but I think that is a separate JS API topic. Closing.
