### ISSUE TITLE
Should catch blocks have type signatures.

### ISSUE THREAD

**Issue by KarlSchimpf** [WebAssembly/exception-handling#4]
The current proposal adds a type signature that must be the same as the try block. Should we be doing this.

**Comment by flagxor** [comment]
Unsure. The use of signatures for things that could be inferred has always struck me as inefficient. However, having the signatures might be consistent with elsewhere.
On the other hand we don't do this for if-else-end.

**Comment by KarlSchimpf** [comment]
In PR #6, catch blocks no longer have a type, since they appear is part of the try construct. The "try" instruction defines the block signature for all paths followed, including code in a catch block.

**Comment by KarlSchimpf** [comment]
Since the proposal no longer suggests this, closing. If you disagree, you can always reopen.
