### ISSUE TITLE
Clarify catch block syntax

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/exception-handling#76]
The current version of V8 seems to require an index on the catch instruction. I receive:

`CompileError: AsyncCompilation: Compiling wasm function "simple2" failed: Invalid exception index: 0 @+38`

Where the 0 is a varuint32 number after the catch instruction in the binary code

```
(module
  (func $simple2 (result i32) (local i32) (local anyref)
    try
      i32.const 5
      i32.const 0
      i32.div_s
      set_local 0
    catch 0
      set_local 1
      i32.const 2
      set_local 0
    end
    get_local 0
    return
  )
).
```

The original code look like:

        static int simple2() {
            int r;
            try {
                r = 5 / 0;
            } catch(Exception ex ) {
                r = 2;
            }
            return r;
        }

What this index means after the catch operation? Or is this simple n bug in the early implementation in V8: 7.3.0-node.5 (candidate)

**Comment by aheejin** [comment]
The [first version of the proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/old/Exceptions.md) had an index argument in `catch` instruction, but we recently switched to the [current version of the proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/Exceptions.md), in which `catch` does not have any argument. Currently AFAIK V8's prototype implementation is based on the first proposal and has not yet switched to the second one. (LLVM toolchain implementation as well)

By the way, how did you generate the wasm code above from your C++ source code?

For the V8 error message, @mstarzinger, do you know anything about that?

**Comment by Horcrux7** [comment]
Thanks for the anwser. This help me.

I have create the binary with JWebAssembly, a Java to WASM compiler on wich I working.

**Comment by aheejin** [comment]
Now v8 has a working implementation of the current (= second) proposal, and you can enable it with `--experimental-wasm-eh`. C++ toolchain implementation is still in progress, but we plan to test it soon. Anyway, closing this.
