### ISSUE TITLE
Can I save an exception to a local variable?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/exception-handling#77]
Exist an exception value of type `except_ref` only on the stack or can I safe it also in a local variable? Which type should the local variable have?

I try the follow code with wabt:
```
(module
  (func $foo (result i32) (local $ex anyref)
    try
      i32.const 5
      i32.const 0
      i32.div_s
      return
    catch
      local.set 0
      i32.const 2
      return
    end
  )
)
```
and receive:
`error: type mismatch in local.set, expected [anyref] but got [except_ref]`

The using of a local type `except_ref` work also not. 

If there would be some test code then it can be very helpful.

**Comment by rossberg** [comment]
Either should work, but probably isn't fully implemented yet.

**Comment by aheejin** [comment]
I think this should work in in v8 by now.
