### ISSUE TITLE
Inconsistency between except_ref and anyref/anyfunc

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/exception-handling#79]
This proposal spells the type `except_ref` with `_`, but the official spec and the Reference Type proposal write the reference types `anyref` and `anyfunc` without `_`. I think the spelling of these types should be consistent.

**Comment by rossberg** [comment]
I'd propose `exnref`, which is shorter while using a somewhat more established abbreviation.

(Note that `anyfunc` has been renamed to `funcref`.)

**Comment by binji** [comment]
`exnref` seems OK to me. I haven't seen `exn` much before, but a quick search shows it's common in ML- and scheme-like languages.

**Comment by gahaas** [comment]
`exnref` sounds good to me.

**Comment by mstarzinger** [comment]
+1 to exnref from my side as well (sorry for being late to the party).

**Comment by aheejin** [comment]
Changed in
- LLVM: https://github.com/llvm/llvm-project/commit/9f96a58cccb63110ca9515644c454620c86c566d
- Binaryen: WebAssembly/binaryen#2224
- V8: https://github.com/v8/v8/commit/fd1a211c3701a5831c6b9f33bdeeb6403e7f5d7b

Closing the issue.
