### ISSUE TITLE
Is `rethrow` necessary?

### ISSUE THREAD

**Issue by Abion47** [WebAssembly/exception-handling#8]
I'm not sure what separates a `rethrow` from just `throw`. In implementation, the instructions would have to do work to find out what the contextual exception that a `rethrow` would be referring to, but it seems like just rethrowing the exception with just a `throw ex` would be perfectly acceptable as well as simpler to implement.

**Comment by flagxor** [comment]
This is intended to accommodate the case of exception types that are unknown to the current module (i.e. haven't been imported or are local).
For example if one module throws, or a JS exception occurs, another module that called into it might need to catch the exception (via else) to do proper cleanup (a destructor or finally), but not be able to manipulate the exception beyond rethrowing when done.

**Comment by Abion47** [comment]
I'm still not sure I follow. What would the benefit of using `rethrow` over `throw ex` be in that situation (beyond number of characters), or what would render `throw ex` unusable? I mean, it seems like `rethrow` is glorified syntactic sugar at this point.

**Comment by binji** [comment]
`throw` as currently specified in the proposal constructs a new exception of a given exception type, popping arguments from the stack. `rethrow` will not construct a new exception, but instead throw the current exception.

**Comment by Abion47** [comment]
I would say that it should be something else's job to construct the new exception and `throw`'s job just to report it to the enclosing block. That way, the functionality of `throw` and `rethrow` would be largely identical, which would remove the need for `rethrow` and open up an op code for something else (such as the `finally` block being discussed in another issue thread).

**Comment by binji** [comment]
That's possible but would require being able to store an exception on the operand stack, which this solution nicely avoids.

**Comment by KarlSchimpf** [comment]
I think we are better off keeping exceptions opaque, in that it reduces issues for handling unknown, imported exceptions. The current proposal keeps us from having to extend the operand stack, locals, and accessors for a (new) exception type.

**Comment by Abion47** [comment]
That's a fair enough point on that issue. I'm just worried that without an opcode for `finally`, then languages that do support `finally` wouldn't be able to be fully represented. Although, maybe there are other ways to achieve the same thing, such as `goto`ing the `finally` code and running it before throwing the exception (if any).
