### ISSUE TITLE
Factors behind using `else` for default catch block

### ISSUE THREAD

**Issue by Abion47** [WebAssembly/exception-handling#9]
I have a bit of a two-fold issue with using `else` as the keyword for the default catch block. 

First, it's a bit of an awkward word choice for the operation conceptually. For example, with just a try block with no special catches:

```
try
  instruction
else
  instruction
end
```

Conceptually, it's "try to do something, else do something". Compared to the `catch` keyword,  it doesn't seem to quite fit. (I fully accept that this is probably a subjective opinion.)

My second problem is that its use conflicts with the current implementation of `else` as a companion to `if`. The compiler would have to be able to tell the difference between an `else` block attached to an `if` block or one attached to a `try/catch` block. While that's certainly possible to do, I can't help but wonder if using a different keyword would reduce the necessary complexity. Even using `catch` without an immediate seems like it would be simpler (not to mention easier to conceptualize).

So with my above two issues laid out, I would propose to either use the `catch` keyword without an immediate for the default catch block, or to use a different keyword like `default` that more accurately conveys the meaning of that block.

**Comment by flagxor** [comment]
Yeah, I think using the 'else' opcode here will lead to a parsing ambiguity.
We should probably do 'default' or 'catch-all'.

**Comment by binji** [comment]
Seems like we should be able to just bind the `else` to the nearest `if` or `try`, just like `end` does currently.

Also: `catch` can't be made to work both with and without an immediate. It's necessary to be able to read the `catch` opcode and determine whether the following bytes are part of the opcode or not.

**Comment by Abion47** [comment]
I like the `catch-all` idea, as it captures the idea best of all. Though I'd probably remove the hyphen and make it just `catchall` so as to not run into issues with the `-` character (if that's even a concern).

I thought I would suggest the alternative with `catch`, since as that's how some languages like C# does it so it's certainly possible, though I'm not sure if the current implementation would easily allow something like that.

Regardless, I'd argue that it would still be simpler to go with something like `catchall` so as to reduce the amount of rework imposed on the current implementation as well as lighten the amount of work the compiler would have to do.

**Comment by binji** [comment]
@Abion47 You may want to take a look a the [WebAssembly spec](http://webassembly.github.io/spec). WebAssembly does have a text format (the spec for this is currently being worked on by @rossberg-chromium), but WebAssembly is primarily specified in terms of its binary format, which is what the browsers consume.

**Comment by rossberg** [comment]
It should be fine to call it `catch_all` or something in the text format (and abstract syntax) but still use the same opcode as `else` in the binary format. Either way, there is no ambiguity.

**Comment by flagxor** [comment]
Sorry, head not screwed on. We have closing ends.
There's no parsing ambiguity.
else saves a byte code.
I suppose we could sugar it as some other name, but less magic == better.

**Comment by KarlSchimpf** [comment]
I do not like `catchall` in that it doesn't catch all exceptions, only those not caught by other catches in the try block.

Syntactically, I like `catch default` (as two tokens). Semantically, I don't think we should introduce a new opcode, since use of existing opcode `else` is unambiguous.

**Comment by Abion47** [comment]
So I've been thinking, and I realized that I was mistaken about C# doing the catch without an immediate to denote the "catch default" case. IIRC, `catch` in C# is just a syntactic shortcut to typing `catch (Exception ex)`, so rather than it just knowing to throw any kind of exception, it uses a base scenario in which the type of exception caught unambiguously covers every kind of potential exception that _could_ be caught. Since the proposal currently uses a `varuint32` to declare the type of exception thrown/caught, would it be possible to reserve a specific value (e.g. `0`) to mean a similar type of deal?

But in any case, this is out of curiosity at this point. I know that Web Assembly is primarily a byte format, and the bulk of my concern was over the textual representation. Using `catch default` or `catch all` in text that compiles to the same op code as `else` would dissuade my concerns just as well.

**Comment by rossberg** [comment]
On 11 May 2017 at 21:08, KarlSchimpf <notifications@github.com> wrote:

> I do not like catchall in that it doesn't catch all exceptions, only
> those not caught by other catches in the try block.
>

Well, catch-all is a common term for this. It catches all exceptions in the
same way `catch 5` catches exception 5, namely, only if there hasn't been
any previous handler that already caught it (you could have two `catch 5`
as well). ;)

**Comment by KarlSchimpf** [comment]
Since a number of people prefer catch-all (or catch_all), changing to use that.

**Comment by KarlSchimpf** [comment]
Appears that consensus has been reached. Closing. If you disagree, feel free to repoen
