### ISSUE TITLE
Update constant value for exnref type

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/exception-handling#92]
We are currently using -0x18, but that slot just used by reference-types for nullref:
https://github.com/WebAssembly/reference-types/pull/66

**Comment by aheejin** [comment]
I think that -18 in WebAssembly/reference-types#66 is in decimal, while our -0x18 is in hexadecimal.

**Comment by sbc100** [comment]
Oh, that case wabt is just wrong I guess: https://github.com/WebAssembly/wabt/blob/76ff3af40040a90c15b6b9f2614f3a3869dbdab1/src/common.h#L217

I'll propose a change there.

**Comment by aheejin** [comment]
Not sure what you mean. The current wabt implementation looks correct. Exnref is -0x18, in hexadecimal.
