### ISSUE TITLE
Advance to phase 2?

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/exception-handling#95]
Currently #93, PR to update overview on traps and JS API, is out for review, and we are discussing whether `rethrow` and `br_on_exn` should trap on `nullref` in #90. After these two are landed / resolved, I'd like to propose to advance the EH proposal to phase 2. Do people think there are any remaining concerns before we advance?

**Comment by aheejin** [comment]
PR to resolve nullref trap issue: #97

**Comment by aheejin** [comment]
I was planning to propose for a vote sometime in January in a video CG meeting, but given that we have an in-person meeting just a few more weeks away, would it be better to do the vote on the in-person CG meeting? I don't mind either though.

**Comment by rossberg** [comment]
Yes, I think the in-person meeting is a good time.

**Comment by aheejin** [comment]
We decided to advance the proposal to phase 2 in the [in-person CG meeting in Feb](https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md). Thank you!
