### ISSUE TITLE
Move event section before global section

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/exception-handling#98]
The proposal currently positions the event section after the global section. However, it is perceivable that under some future extensions, the initialiser expressions for a global might be generalised such that they can contain instructions that refer to exceptions. At the same time, there is no apparent reason to assume that exception defs would ever need to refer to globals.

Thus, in order to keep validation as single-pass as possible, I'd propose switching the order of global and event section in the binary format.

**Comment by aheejin** [comment]
Sounds good. I [requested](https://bugs.chromium.org/p/v8/issues/detail?id=10176) this change in v8. Will change this in LLVM / Binaryen/ Wabt after V8 change is implemented.

**Comment by aheejin** [comment]
This has been reflected in:
LLVM: https://github.com/llvm/llvm-project/commit/f93426c5b9646625aee728b1bd5066e6dc381b73
V8: https://github.com/v8/v8/commit/92bd7818b7f4d1d6ae9d51532e26e692cec67c99
Binaryen: WebAssembly/binaryen#2708
Wabt: WebAssembly/wabt#1374

Closing this.
